/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE weasBaseService PLEASE EDIT ../weas.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Weas } from '../../domain/skaff_db/weas';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../weas.service.ts
 */

/*
 * SCHEMA DB weas
 *
	{
		tipo: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		asdfg: {
			type: Schema.ObjectId,
			ref : "weas"
		},
	}
 *
 */
@Injectable()
export class WeasBaseService {

    contextUrl: string = environment.endpoint + '/weas';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * weasService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Weas): Observable<Weas> {
        return this.http
            .post<Weas>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * weasService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * weasService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Weas> {
        return this.http
            .get<Weas>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * weasService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Weas[]> {
        return this.http
            .get<Weas[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * weasService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Weas): Observable<Weas> {
        return this.http
            .post<Weas>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
